name: ndvi
channels:
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.3.0
  - _openmp_mutex=4.5
  - affine=2.4.0
  - aom=3.9.1
  - attrs=25.4.0
  - backports.zstd=1.3.0
  - blosc=1.21.6
  - branca=0.8.2
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - cairo=1.18.4
  - certifi=2025.11.12
  - charset-normalizer=3.4.4
  - click=8.3.1
  - click-plugins=1.1.1.2
  - cligj=0.7.2
  - colorama=0.4.6
  - contourpy=1.3.3
  - cycler=0.12.1
  - dav1d=1.2.1
  - double-conversion=3.3.1
  - expat=2.7.3
  - fiona=1.10.1
  - folium=0.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.1
  - freetype=2.14.1
  - freexl=2.0.0
  - gdal=3.10.0
  - geopandas=1.1.2
  - geopandas-base=1.1.2
  - geos=3.13.0
  - geotiff=1.7.4
  - graphite2=1.3.14
  - h2=4.3.0
  - harfbuzz=11.0.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - jinja2=3.1.6
  - joblib=1.5.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libarchive=3.7.7
  - libavif16=1.3.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libclang13=21.1.7
  - libcurl=8.17.0
  - libde265=1.0.15
  - libdeflate=1.22
  - libexpat=2.7.3
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgdal-core=3.10.0
  - libglib=2.84.0
  - libgomp=15.2.0
  - libheif=1.18.2
  - libhwloc=2.12.1
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.1.2
  - libkml=1.3.0
  - liblapack=3.11.0
  - libpng=1.6.53
  - librttopo=1.1.0
  - libspatialite=5.1.0
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libxslt=1.1.43
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - lz4-c=1.9.4
  - lzo=2.10
  - mapclassify=2.10.0
  - markupsafe=3.0.3
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - minizip=4.0.6
  - mkl=2025.3.0
  - munkres=1.1.4
  - networkx=3.6.1
  - numpy=2.4.0
  - openjpeg=2.5.3
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.3
  - pcre2=10.44
  - pillow=11.3.0
  - pip=25.3
  - pixman=0.46.4
  - proj=9.5.1
  - pthread-stubs=0.4
  - pyogrio=0.10.0
  - pyparsing=3.3.1
  - pyproj=3.7.1
  - pyside6=6.9.0
  - pysocks=1.7.1
  - python=3.12.12
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.3
  - python_abi=3.12
  - pytz=2025.2
  - qhull=2020.2
  - qt6-main=6.9.0
  - rasterio=1.4.3
  - rav1e=0.7.1
  - requests=2.32.5
  - scikit-learn=1.8.0
  - setuptools=80.9.0
  - shapely=2.0.7
  - six=1.17.0
  - snappy=1.2.2
  - snuggs=1.4.7
  - sqlite=3.51.0
  - svt-av1=3.1.2
  - tbb=2022.3.0
  - threadpoolctl=3.6.0
  - tk=8.6.15
  - tornado=6.5.4
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - unicodedata2=17.0.0
  - uriparser=0.9.8
  - urllib3=2.6.2
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - x265=3.5
  - xerces-c=3.2.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2025.11.0
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - scipy==1.16.3
prefix: D:\Projects\conda_envs\ndvi
